name: Test

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Gheckout qson
        uses: actions/checkout@v5
        with:
          repository: qgdev-ir/qson
          path: qson

      - name: Install qson
        run: sudo make install
        working-directory: qson

      - name: Gheckout qstruct
        uses: actions/checkout@v5
        with:
          repository: qgdev-ir/qstruct
          path: qstruct

      - name: Install qstruct
        run: sudo make install
        working-directory: qstruct

      - name: Compile
        run: make

      - name: Test
        run: make test
        env:
          LD_LIBRARY_PATH: build

